#!/bin/bash

sed -i 's/\#\[ignore\]\/\/docker/\/\/#[ignore]\/\/docker/g' src/mod.rs
sed -i 's/\#\[ignore\]\/\/docker/\/\/#[ignore]\/\/docker/g' src/terminal.rs
sed -i 's/\#\[ignore\]\/\/docker/\/\/#[ignore]\/\/docker/g' src/list.rs
sed -i 's/\#\[ignore\]\/\/docker/\/\/#[ignore]\/\/docker/g' src/bin/main.rs
sed -i 's/\#\[ignore\]\/\/docker/\/\/#[ignore]\/\/docker/g' src/fuzzy.rs
sed -i 's/\#\[ignore\]\/\/docker/\/\/#[ignore]\/\/docker/g' tests/list_files.rs
