#!/bin/bash

sed -i 's/\#\[ignore\]\/\/play/\/\/#[ignore]\/\/play/g' src/mod.rs
sed -i 's/\#\[ignore\]\/\/play/\/\/#[ignore]\/\/play/g' src/terminal.rs
sed -i 's/\#\[ignore\]\/\/play/\/\/#[ignore]\/\/play/g' src/list.rs
sed -i 's/\#\[ignore\]\/\/play/\/\/#[ignore]\/\/play/g' src/bin/main.rs
